// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_Skynetz.Data;

#nullable disable

namespace Project_Skynetz.Migrations
{
    [DbContext(typeof(SkynetzContext))]
    partial class SkynetzContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project_Skynetz.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IncludedMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IncludedMinutes = 30,
                            Name = "FaleMais 30"
                        },
                        new
                        {
                            Id = 2,
                            IncludedMinutes = 60,
                            Name = "FaleMais 60"
                        },
                        new
                        {
                            Id = 3,
                            IncludedMinutes = 120,
                            Name = "FaleMais 120"
                        });
                });

            modelBuilder.Entity("Project_Skynetz.Models.Rate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DestinationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerMinute")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Rates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DestinationCode = "016",
                            OriginCode = "011",
                            PricePerMinute = 1.90m
                        },
                        new
                        {
                            Id = 2,
                            DestinationCode = "011",
                            OriginCode = "016",
                            PricePerMinute = 2.90m
                        },
                        new
                        {
                            Id = 3,
                            DestinationCode = "017",
                            OriginCode = "011",
                            PricePerMinute = 1.70m
                        },
                        new
                        {
                            Id = 4,
                            DestinationCode = "011",
                            OriginCode = "017",
                            PricePerMinute = 2.70m
                        },
                        new
                        {
                            Id = 5,
                            DestinationCode = "018",
                            OriginCode = "011",
                            PricePerMinute = 0.90m
                        },
                        new
                        {
                            Id = 6,
                            DestinationCode = "011",
                            OriginCode = "018",
                            PricePerMinute = 1.90m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
